### ISSUE TITLE
US2: Provision project to use Totem V3

### ISSUE THREAD

**Issue by mmoulton** [totem/totem-v3#2]
As a **developer**, I need to know how to provision my application for deployment on Totem V3

#### Acceptance Criteria

* Documentation on how to provision a new project for use on Totem V3
* Github repo of new project has a configured webhook for at least push events

Note:
- As part of this story, we are not expected to have a CD pipeline.  (It will come in future story)

**Comment by sukrit007** [comment]
@mmoulton can we define constraints for basic application  e.g: 
- Uses single port (either public or private)
- Does not use any private repositories like private NPM, Nexus as part of the build
- Does not require any credentials  at runtime

In addition,  I believe this story is for manually deploying to totem v3 cluster and we will have a separate story for continuous deploy.  Thoughts ?

**Comment by sukrit007** [comment]
@mmoulton  based on our discussion, we decided to perform build during the first story.  I think this might need to be broken down further based on following questions: 

- Do we want the ability to configure and build any branch?
- Do we want to set it up so that it is built in the continuous fashion for the current story?
- Do we want to support legacy totem.yml transformation as part of the current story?  (I assume no , and it will be its own story)

I was wondering if as part of the next story we simply solve the problem: *How do I setup my repository to be enabled for continuous deployment with totem-v3 ?*

**Comment by sukrit007** [comment]
@mmoulton  for API authentication,  I will currently use IAM User.  In future user stories (if needed) we can explore other options like
- Cognito user pool
- API Key
- Custom auth

IAM Auth will work great with totem CLI.  Might not be the best use case for UI though.
